### PR TITLE
Updating to 1.1.0

### PR DESCRIPTION
**Pull request by krischer**

### CODE REVIEW

**Comment by krischer** [comment]
@conda-forge/core  Sorry to ping you but I'm not really sure what is wrong here. Do I need to update all the non-recipe related things from the core feedstock repository?

**Comment by jakirkham** [comment]
Are you referring to [re-rendering](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock)? Yes, that will need to be done.

**Comment by jakirkham** [comment]
~~Also you need to add `setuptools` as a build requirement.~~

Edit: I guess you already had this. Though this [failure](https://circleci.com/gh/conda-forge/instaseis-feedstock/13) suggests otherwise.

**Comment by krischer** [comment]
I guess so?

I just did it but not a lot changed. Lets see what happens.

Thanks!

**Comment by jakirkham** [comment]
So `.gitignore` seems to have gotten executable permissions somehow. Could you please revert that? Also do you know how that happened?

**Comment by jakirkham** [comment]
> I just did it but not a lot changed.

The Miniconda download URLs changed. Hence why this was required.

**Comment by krischer** [comment]
> So .gitignore seems to have gotten executable permissions somehow. Could you please revert that? Also do you know how that happened?

`conda smithy rerender` - I also wondered why. So this is not intentional?

**Comment by krischer** [comment]
> Also you need to add setuptools as a build requirement.

It already is a requirement.

**Comment by jakirkham** [comment]
> > So .gitignore seems to have gotten executable permissions somehow. Could you please revert that? Also do you know how that happened?
> 
> `conda smithy rerender` - I also wondered why.

Me too. Is it reproducible?

> So this is not intentional?

Nope, we only set executable permissions intentionally on 2 files: `checkout_merge_commit.sh` and `run_docker_build.sh`. Everything else should have the same permissions as it did in `conda-smithy`. Namely `100644`.

**Comment by jakirkham** [comment]
> > Also you need to add setuptools as a build requirement.
> 
> It already is a requirement.

Yep, please see the edit in that comment.

**Comment by krischer** [comment]
> Me too. Is it reproducible?

No. I just tried a couple of tries from various stages of the branch. I'm not sure what happened but I guess it was somehow my doing.

**Comment by jjhelmus** [comment]
I've seen permission changes occurring during re-rendering also, although they are not reliable.  I think there must be a race condition somewhere in the re rendering script.

**Comment by krischer** [comment]
Re-rendering the feedstock did the trick. Thanks for your help.

I'll open an issue if I ever encounter the permission problem again.

**Comment by jakirkham** [comment]
> I'll open an issue if I ever encounter the permission problem again.

Please do.

> I've seen permission changes occurring during re-rendering also, although they are not reliable.

If you have some reproducible cases (even if it is not every time), it would be good to have a `conda-smithy` issue so we can document these and try to address them.

> I think there must be a race condition somewhere in the re rendering script.

So there are only two cases where we actually set permissions as noted [above](https://github.com/conda-forge/instaseis-feedstock/pull/7#issuecomment-258852444). Thus far I haven't seen a case where that doesn't work as intended. Not to say it can't happen, just that hasn't.

However, I have seen cases where other files do get the wrong permissions. ( https://github.com/conda-forge/conda-smithy/issues/365 ) As we don't set the file permissions at all in those cases, I doubt these are race conditions, but unusual corner cases of different file systems or combinations of file systems (one mounted in the context of another). It may be that we need to just always set the permissions we want to make sure we get what we expect. TBH that is exactly why we are setting the file permissions on the two executable files.

**Pull request merged**
