### PR TITLE
Trying to workaround an issue with the team update script

### PR DESCRIPTION
**Pull request by krischer**
See https://github.com/conda-forge/conda-forge.github.io/issues/228

Let's see if it works.

### CODE REVIEW

**Comment by jakirkham** [comment]
The easiest thing I think will be to drop these in `run_test.sh`.

Also please remember to fork and propose changes from your fork, @krischer.

**Comment by krischer** [comment]
> The easiest thing I think will be to drop these in run_test.sh.

Its an issue I suddenly also see locally - I guess one of the dependent packages introduces a backwards incompatible change. I'll have to track it down. I'll do it today.

> Also please remember to fork and propose changes from your fork, @krischer.

Right. I keep forgetting this :-( Sorry about that.

**Comment by krischer** [comment]
Continued in #2.

**Comment by jakirkham** [comment]
Went ahead and deleted the branch as this has been closed and already implemented in the other PR.

**Comment by jakirkham** [comment]
> > The easiest thing I think will be to drop these in run_test.sh.
> 
> Its an issue I suddenly also see locally - I guess one of the dependent packages introduces a backwards incompatible change. I'll have to track it down. I'll do it today.

Yeah we started using `conda-build` to run the team update script some time back as the penalty for having our own code to parse `meta.yaml` for that info was too high. See PR ( https://github.com/conda-forge/conda-forge.github.io/pull/142 ) for this change.

So this definitely should be reported as a `conda-build` bug. If you want to try doing [`git bisect`](https://git-scm.com/docs/git-bisect) to determine what commit let this bug enter `conda-build`, that would be really helpful.

**Comment by krischer** [comment]
I'm honestly not sure why the issue suddenly appeared across all systems but it is not a `conda-build` issue.

`instaseis` is has been tested to death so its a bit of a mystery to me why that bug all of a sudden manifests. Its a subtle thing related to weak-dictionaries and the timing of the garbage collector and it cannot happen in real world scenarios so I did not investigate a lot further but worked around it.

**Pull request closed without merging**
